name: report-on-vulnerabilities

permissions: {}

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kyverno/kyverno
  TAG : release-1.11

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest tag
      id: get-latest-tag
      shell: bash
      run: |
        latest_tag=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[0].name')
        one_tag=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[1].name')
        two_tag=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[2].name')
        all_tags=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[] | select(.name | startsSwith("release"))')
        
        echo "Latest tag: $latest_tag One tag: $one_tag Two tag: $two_tag All tags: $all_tag"