name: report-on-vulnerabilities

permissions: {}

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kyverno/kyverno
  TAG : release-1.11

jobs:
  scan:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.parse-results.outputs.results }}
    steps:
    - name: Get Versions
      run: |
        

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@b77b85c0254bba6789e787844f0585cde1e56320 # v0.8.0 (Trivy v0.34.0)
      with: 
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        format: json
        ignore-unfixed: false
        severity: HIGH,CRITICAL
        output: scan.json
    - name: Parse scan results
      id: parse-results
      continue-on-error: true
      run: |
        VULNS=$(cat scan.json | jq '.Results[] | select(.Target=="ko-app/kyverno") | length')
        if [[ $VULNS -eq 0 ]]
        then
          echo "No vulnerabilities found, halting"
          echo "results=nothing" >> $GITHUB_OUTPUT
        else
          echo "Vulnerabilities found, creating issue"
          echo "results=found" >> $GITHUB_OUTPUT
        fi
    - name: Get latest tag
      id: get-latest-tag
      shell: bash
      run: |
        latest_tag=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[0].name')
        one_tag=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[1].name')
        two_tag=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[2].name')
        all_tags=$(curl -s https://api.github.com/repos/${{ env.IMAGE_NAME }}/tags | jq -r '.[] | select(.name | starts_with("release"))')
        
        echo "Latest tag: $latest_tag One tag: $one_tag Two tag: $two_tag All tags: $all_tag"