name: Check for assigned issues

on:
  pull_request_comment:

jobs:
  check_assigned_issues:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get the author of the comment
        id: get_author
        run: |
          echo "::set-output name=author::$(gh pr comment show --number ${{ github.event.number }} --output=raw | jq -r '.user.login')"

      - name: Check if the author has any assigned issues
        id: check_assigned_issues
        uses: actions/github-script@v5
        with:
          script: |
            const author = process.env.author;
            const issues = await github.issues.listAssigned({ assignee: author });
            if (issues.data.length > 0) {
              return true;
            } else {
              return false;
            }

      - name: Update the comment with meta information
        if: ${{ steps.check_assigned_issues.outputs.result }}
        uses: actions/github-script@v5
        with:
          script: |
            const author = process.env.author;
            const issues = await github.issues.listAssigned({ assignee: author });
            const issueUrl = issues.data[0].html_url;

            await github.issues.updateComment({
              comment_id: ${{ github.event.comment_id }},
              body: `${author}, you have ${issues.data.length} issue(s) assigned to you. Please see [the issue](${issueUrl}) to learn more.`
            });